
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=   # admin
  apiKey: QUJDREVGR0g=  # ABCDEFGH
  password: U3VwZXJTZWN1cmVQYXNz  # SuperSecurePass



## if you have a one or multiple secrets,
you can use the secret as a `env` variable or a `mount them as file`

