
apiVersion: v1
kind: Secret
metadata:
  name: name-secret
type: Opaque
data:
  username: YWRtaW4=   # admin

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  apiKey: QUJDREVGR0g=  # ABCDEFGH

---
apiVersion: v1
kind: Secret
metadata:
  name: pass-secret
type: Opaque
data:
  password: U3VwZXJTZWN1cmVQYXNz  # SuperSecurePass




## if you have a one or multiple secrets,
you can use the secret as a `env` variable or a `mount them as file`
